### ISSUE TITLE
Cannot get any news at all.

### ISSUE THREAD

**Issue by aLECChe** [mumblebaj/MMM-NewsAPI#1]
Cannot get any news at all. With of without country code. And the error returned is null.

![error-001](https://user-images.githubusercontent.com/64255284/129439404-d75d1571-38e2-4f4f-bb42-a5bdc3e28542.JPG)

![error-002](https://user-images.githubusercontent.com/64255284/129439408-b58f7e09-33e8-41c5-bb31-b8d4b35566af.JPG)

Thank you very much.

**Comment by mumblebaj** [comment]
Please Query options:
When using everything, you cannot use the country option.

**Comment by aLECChe** [comment]
I might have found the problem. It seems you cannot just pick one query option, you have to write them all.

![news-001](https://user-images.githubusercontent.com/64255284/129452332-ed1c2e4c-4715-4e38-acce-e252e609b120.JPG)

**Comment by mumblebaj** [comment]
That is not correct.  Please see the README for the usage of the options. The API allows only specific options per "choice". I have added optimal samples for usage.

**Comment by mumblebaj** [comment]
I have made a change that should now work with just supplying the country.
