### ISSUE TITLE
help horizontal/vertical

### ISSUE THREAD

**Issue by greedyvegan** [mumblebaj/MMM-NewsAPI#11]
greetings, I'm trying to change the location of the items in the module and would appreciate some help.
![Screenshot 2024-06-24 at 10 25 22 PM](https://github.com/mumblebaj/MMM-NewsAPI/assets/128918275/22bdb8f2-d698-4a77-ad01-dca89b44d57a)

I'm using the developer mode, but when I put in the #NEWSAPI_article image, header, content, etc I'm drawing a blank.
I want to move the font from underneath to the right of the image and have the footer at the bottom, under the image.
![Screenshot 2024-06-24 at 10 26 47 PM](https://github.com/mumblebaj/MMM-NewsAPI/assets/128918275/271ca159-ecca-42bc-9ca9-6827b56df6eb)

**Comment by greedyvegan** [comment]
> Hi. Unfortunately the default module template not designed like that. You cannot move the text around. You can design your own template if you like and specify that the module should use that.

understood.

> From the template code you would want to move the %DESCRIPTION% out of the content and into it's own div and you can move that div to where you would like it to be.

can I find the div classes or titles that work in custom.css  in the template.html?

**Comment by mumblebaj** [comment]
Morning. Yes, but it will not assist you in doing what you want. The best
option is as described above to design your own custom template and make
use of that. Hence the module was designed so others could create their own
layouts.
