### ISSUE TITLE
news are not loading

### ISSUE THREAD

**Issue by daddysmackdn** [mumblebaj/MMM-NewsAPI#14]
Hi, I can't get the news to load.  it just shows the headers.  below is my config.... please help

                  module: "MMM-NewsAPI",                                                                                           header: "news",                                                                                                            position: "bottom_bar",
        config: {
            apiKey: "xxxxx",
            type: "horizontal",
            choice: "headlines",
            pageSize: 10,
            sortBy: "publishedAt",
            drawInterval: 1000*30,
            templateFile: "template.html",
            fetchInterval: 1000*60*60,                                                                                                 QRCode: true,                                                                                                              query: {                                                                                                                       country: "us",                                                                                                             category: "general",
                q: "",
                qInTitle: "",
                sources: "https://newsapi.org/v2/top-headlines/sources?apiKey=xxxxxx&country=us",                domains: "",
                excludeDomains: "",
                language: "en"

**Comment by mumblebaj** [comment]
Hi. You need to fix the sources. If you enter the following into your browser, it will give you a list of sources that you can select from. 
**https://newsapi.org/v2/top-headlines/sources?apiKey=your-api-key-goes-here&country=us**
Use the id from the list of sources, comma delimited list.
I.e. sample list:
"abc-news,ssociated-press,axios" or you can just select the 2 letter country code, i.e. country:"us"

**Comment by daddysmackdn** [comment]
So. It started working all the sudden. But now my next issue is that the picture is extremely large

**Comment by mumblebaj** [comment]
Are you using `horizontal` or `vertical`? Switch between the two and see what works for you.

**Comment by daddysmackdn** [comment]
both same.. picture is extremely large

**Comment by mumblebaj** [comment]
So, depending on the orientation you are using you can use the below to set the size of the picture: Just swop out the horizontal with vertical if you are using the vertical layout.

```
#NEWSAPI.horizontal .content .articleImage {
   max-width: 5vw;
   max-height: 5vh;
} 
```
