### ISSUE TITLE
Typo in Node_helper.js for qInTitle search causes query fail

### ISSUE THREAD

**Issue by jconno03** [mumblebaj/MMM-NewsAPI#9]
Node_helper.js has an error which causes a news search by title to fail.  qIntTitle should be qInTitle

Line 34: if (q.hasOwnProperty("qInTitle") && q.qInTitle !== "") qs = Object.assign({}, qs, {"qIntTitle":q["qInTitle"]})
Line 74: if (q.hasOwnProperty("qInTitle") && q.qInTitle !== "") qs = Object.assign({}, qs, {"qIntTitle":q["qInTitle"]})

**Comment by mumblebaj** [comment]
Thanks for picking this up. I have pushed a fix for this.
